import { isValidUser } from "app/services/auth.service";
import Head from "next/head";
 
export const getServerSideProps = (ctx) => isValidUser(ctx);
export default function Home() {
  return (
    <>
      <Head>
        <title> </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
    </>
  );
}
